# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 21:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(blank=True, max_length=12)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(height_field=120, upload_to='accounts/photo', width_field=160)),
                ('gender', models.CharField(choices=[('MA', 'male'), ('FE', 'female')], default='', max_length=6)),
            ],
            options={
                'ordering': ['login'],
                'verbose_name': 'userdata',
                'verbose_name_plural': 'userdata',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='name', max_length=60),
        ),
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
