# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170715_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='email',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
