# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170718_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='user', max_length=60),
        ),
    ]
