# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170718_1804'),
        ('accounts', '0006_auto_20170720_1255'), 
    ]

    operations = [
    ]
