# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('place_order', models.BooleanField(default=False, verbose_name='Place Order')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Unit Price')),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Shipping Cost')),
                ('tax_cost', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='TAX')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Subtotal')),
            ],
            options={
                'ordering': ['create_date'],
                'verbose_name': 'Cart',
            },
        ),
    ]
