# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 18:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('coupon_secret', models.CharField(default=b'1c2afa8fff1f45f8bf230316d14856b8', editable=False, max_length=64)),
                ('is_valid', models.BooleanField(default=True)),
                ('value_type', models.CharField(choices=[(b'P', b'percent'), (b'N', b'natural')], default=b'N', editable=False, max_length=1)),
                ('git_type', models.CharField(choices=[(b'P', b'personal_gift'), (b'M', b'mass_gift')], editable=False, max_length=1)),
                ('value', models.PositiveIntegerField()),
                ('expired_date', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999))),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromoGiftCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_used', models.PositiveIntegerField()),
                ('GiftCoupon', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='coupons.GiftCoupon')),
            ],
            options={
                'db_table': 'gift_promo',
            },
        ),
        migrations.CreateModel(
            name='SaleCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('delete_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('coupon_secret', models.CharField(default=b'1c2afa8fff1f45f8bf230316d14856b8', editable=False, max_length=64)),
                ('is_valid', models.BooleanField(default=True)),
                ('value_type', models.CharField(choices=[(b'P', b'percent'), (b'N', b'natural')], default=b'P', max_length=1)),
                ('sale_type', models.CharField(choices=[(b'I', b'Item sale'), (b'C', b'category_sale')], max_length=1)),
                ('default_value', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField()),
                ('expired_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserGiftCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_date', models.DateTimeField(blank=True)),
                ('GiftCoupon', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='coupons.GiftCoupon')),
            ],
            options={
                'db_table': 'gift_user',
            },
        ),
        migrations.CreateModel(
            name='CategorySaleCoupon',
            fields=[
                ('salecoupon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coupons.SaleCoupon')),
                ('value', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_coupon_related', to='products.Category')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
            bases=('coupons.salecoupon',),
        ),
        migrations.CreateModel(
            name='ItemSaleCoupon',
            fields=[
                ('salecoupon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coupons.SaleCoupon')),
                ('value', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_sale_product_related', to='products.Product')),
                ('sale_coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_sale_coupon_related', to='coupons.SaleCoupon')),
            ],
            options={
                'ordering': ['pk'],
                'abstract': False,
            },
            bases=('coupons.salecoupon',),
        ),
        migrations.AddField(
            model_name='categorysalecoupon',
            name='sale_coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_sale_coupon_related', to='coupons.SaleCoupon'),
        ),
    ]
