# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcoupon',
            name='coupon_secret',
            field=models.CharField(default=b'cf4c8dde956448a2a770c534f2688b71', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='salecoupon',
            name='coupon_secret',
            field=models.CharField(default=b'cf4c8dde956448a2a770c534f2688b71', editable=False, max_length=64),
        ),
    ]
