# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20170718_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcoupon',
            name='coupon_secret',
            field=models.CharField(default=b'a7e5192072a048289bebbee2136f5145', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='salecoupon',
            name='coupon_secret',
            field=models.CharField(default=b'a7e5192072a048289bebbee2136f5145', editable=False, max_length=64),
        ),
    ]
