# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20170718_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcoupon',
            name='coupon_secret',
            field=models.CharField(default=b'61df8627f2ce465c95ff4e96244d4182', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='salecoupon',
            name='coupon_secret',
            field=models.CharField(default=b'61df8627f2ce465c95ff4e96244d4182', editable=False, max_length=64),
        ),
    ]
