# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20170718_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcoupon',
            name='coupon_secret',
            field=models.CharField(default=b'477a538c29d34d2bb66533c5a951c92c', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='salecoupon',
            name='coupon_secret',
            field=models.CharField(default=b'477a538c29d34d2bb66533c5a951c92c', editable=False, max_length=64),
        ),
    ]
