# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_auto_20170718_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcoupon',
            name='coupon_secret',
            field=models.CharField(default=b'cfa06964f61f45e8b70bcf967beb0605', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='salecoupon',
            name='coupon_secret',
            field=models.CharField(default=b'cfa06964f61f45e8b70bcf967beb0605', editable=False, max_length=64),
        ),
    ]
