# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_auto_20170719_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcoupon',
            name='coupon_secret',
            field=models.CharField(default=b'68ff094df7da47a9abc6c55e144b2ac1', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='salecoupon',
            name='coupon_secret',
            field=models.CharField(default=b'68ff094df7da47a9abc6c55e144b2ac1', editable=False, max_length=64),
        ),
    ]
